# Generated by Django 3.0.2 on 2020-09-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('CM0', 'COFFEE_MACHINE_LARGE'), ('CM1', 'COFFEE_MACHINE_SMALL'), ('EM0', 'ESPRESSO_MACHINE')], max_length=3)),
                ('water_line_compatible', models.BooleanField()),
                ('model_type', models.IntegerField(choices=[('CM0', 'COFFEE_MACHINE_LARGE'), ('CM1', 'COFFEE_MACHINE_SMALL'), ('EM0', 'ESPRESSO_MACHINE')])),
                ('sku', models.CharField(blank=True, editable=False, max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('CP0', 'COFFEE_POD_LARGE'), ('CP1', 'COFFEE_POD_SMALL'), ('EP0', 'ESPRESSO_POD')], max_length=3)),
                ('coffee_flavor', models.IntegerField(choices=[(0, 'COFFEE_FLAVOR_VANILLA'), (1, 'COFFEE_FLAVOR_CARAMEL'), (2, 'COFFEE_FLAVOR_PSL'), (3, 'COFFEE_FLAVOR_MOCHA'), (4, 'COFFEE_FLAVOR_HAZELNUT')])),
                ('pack_size', models.IntegerField(choices=[(1, 1), (3, 3), (5, 5), (7, 7)])),
                ('sku', models.CharField(blank=True, editable=False, max_length=5, unique=True)),
            ],
        ),
    ]
