# Generated by Django 3.0.2 on 2020-09-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeemachine',
            name='model_type',
            field=models.IntegerField(choices=[(1, 'BASE_MODEL'), (2, 'PREMIUM_MODEL'), (3, 'DELUXE_MODEL')]),
        ),
        migrations.AlterField(
            model_name='coffeemachine',
            name='product_type',
            field=models.CharField(choices=[('CM1', 'COFFEE_MACHINE_LARGE'), ('CM0', 'COFFEE_MACHINE_SMALL'), ('EM0', 'ESPRESSO_MACHINE')], max_length=3),
        ),
        migrations.AlterField(
            model_name='coffeepod',
            name='product_type',
            field=models.CharField(choices=[('CP1', 'COFFEE_POD_LARGE'), ('CP0', 'COFFEE_POD_SMALL'), ('EP0', 'ESPRESSO_POD')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='coffeemachine',
            unique_together={('sku', 'water_line_compatible')},
        ),
    ]
