# Generated by Django 3.0.2 on 2020-09-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200913_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeemachine',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=5),
        ),
    ]
